Start emitting overloaded methods.  Add support for [[ignore]] and [[rename]] instead of implementing terrible auto-renaming.
With all the newly defined methods, android-28-sys may be pushing rustc's limits - I'm consistently getting this error:

C:\local\bindgen-jni>cargo +stable build   --all            --all-features
   Compiling android-28-sys v0.0.0 (C:\local\bindgen-jni\examples\android-28-sys)
error: failed to build archive: The end of the file was unexpectedly encountered

error: aborting due to previous error

error: Could not compile `android-28-sys`.